monolog:
    channels:
        - deprecation
    handlers:
        main:
            type: rotating_file
            max_files: 50
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event", "!doctrine", "!deprecation"]
        deprecation:
            type: rotating_file
            max_files: 20
            path: "%kernel.logs_dir%/%kernel.environment%-deprecations.log"
            level: debug
            channels: [deprecation]
        errors:
            type: rotating_file
            max_files: 50
            path: "%kernel.logs_dir%/%kernel.environment%-errors.log"
            level: error
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console", "!deprecation"]

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50
            nested:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
