nelmio_api_doc:
    documentation:
        info:
            title: Taskana
            description: Api endpoints
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
