version: '3'

networks:
  projects_network:
    name: projects_network

services:
  app_server:
    container_name: app_server
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - ${APP_PORT}:443
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      db_server:
        condition: service_healthy
    networks:
      - projects_network
  
  db_server:
    container_name: db_server
    image: mysql
    ports:
      - ${DB_PORT}:3306
    command: [
      '--default_authentication_plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_TCP_PORT: "3306"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_USER_PASSWORD}"
    restart: always
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$DB_ROOT_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - projects_network

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}
    volumes:
      - adminer_data:/var/www/html
    depends_on:
      db_server:
        condition: service_healthy
    networks:
      - projects_network

  redis_server:
    container_name: redis_server
    image: redis:latest
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_PORT: "${REDIS_PORT}"
    networks:
      - projects_network

volumes:
  db_data:
  adminer_data:
  redis_data:
