version: '3'

networks:
  taskana_network:
    name: taskana_network

services:
  taskana_app:
    container_name: taskana_app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - ${APP_PORT}:80
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      taskana_db:
        condition: service_healthy
    networks:
      - taskana_network

  taskana_db:
    container_name: taskana_db
    image: mysql
    command: [
      '--default_authentication_plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
      - taskana_db_data:/var/lib/mysql
    environment:
      MYSQL_TCP_PORT: "3306"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_USER_PASSWORD}"
    restart: always
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$DB_ROOT_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - taskana_network

  taskana_db_test:
    container_name: taskana_db_test
    image: mysql
    command: [
      '--default_authentication_plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - taskana_db_test_data:/var/lib/mysql
    environment:
      MYSQL_TCP_PORT: "3306"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_USER_PASSWORD}"
    restart: always
    networks:
      - taskana_network

volumes:
  taskana_db_data:
  taskana_db_test_data:
